version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: jarvis@123
      MYSQL_DATABASE: db0,db1
      MYSQL_USER: jarvis
      MYSQL_PASSWORD: jarvis@123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - backend

volumes:
  mongodb_data:
    driver: local
  mysql_data:
    driver: local

networks:
  backend:
    driver: bridge